# Generated by Django 5.2.11 on 2026-02-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa do Veículo')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('escritorio', models.CharField(max_length=100, verbose_name='Escritório Responsável')),
                ('status', models.CharField(choices=[('pre_localizado', 'Pré-localizado'), ('localizado', 'Localizado'), ('apreendido', 'Apreendido')], default='pre_localizado', max_length=20, verbose_name='Situação atual')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
