# Generated by Django 5.2.11 on 2026-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='usuario_acesso',
            field=models.CharField(default='admin', max_length=100, verbose_name='Nome de Acesso'),
        ),
    ]
